import { StyleSheet } from "react-native";
import { Colors } from "../../lib/colors";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: Colors.surface,
  },
  hamburgerIcon: { fontSize: 22, color: Colors.text },
  headerTitle: { fontSize: 18, fontWeight: "bold", color: Colors.secondary },
  scroll: { padding: 16, paddingBottom: 32 },
  avatarWrapper: {
    alignItems: "center",
    marginBottom: 24,
  },
  avatar: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: Colors.card,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: Colors.primary,
    marginBottom: 12,
  },
  avatarText: {
    fontSize: 36,
    color: Colors.secondary,
  },
  userName: {
    fontSize: 20,
    fontWeight: "bold",
    color: Colors.text,
  },
  userEmail: {
    color: Colors.textMuted,
    fontSize: 14,
    marginTop: 2,
  },
  memberBadge: {
    backgroundColor: Colors.card,
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 4,
    marginTop: 8,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  memberText: {
    color: Colors.textMuted,
    fontSize: 12,
  },
  sectionTitle: {
    fontSize: 13,
    color: Colors.textMuted,
    fontWeight: "bold",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 10,
    marginTop: 8,
  },
  label: {
    color: Colors.textMuted,
    fontSize: 13,
    marginBottom: 6,
    marginTop: 12,
  },
  input: {
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 12,
    color: Colors.text,
    fontSize: 15,
  },
  inputDisabled: {
    opacity: 0.5,
  },
  buttonRow: {
    flexDirection: "row",
    marginTop: 24,
    marginHorizontal: -5,
  },
  editBtn: {
    flex: 1,
    marginHorizontal: 5,
    backgroundColor: Colors.primary,
    borderRadius: 10,
    paddingVertical: 13,
    alignItems: "center",
  },
  editBtnText: { color: Colors.white, fontWeight: "bold", fontSize: 14 },
  logoutBtn: {
    flex: 1,
    marginHorizontal: 5,
    backgroundColor: "transparent",
    borderRadius: 10,
    paddingVertical: 13,
    alignItems: "center",
    borderWidth: 1,
    borderColor: Colors.error,
  },
  logoutBtnText: { color: Colors.error, fontWeight: "bold", fontSize: 14 },
});
